version: "2"
services:
  stock-event-post-extension:
    image: openlmis/dev:6
    volumes:
      - '.:/app'
      - 'gradlecache:/gradle'
    env_file: .env
volumes:
  gradlecache:
    external: false
